### ISSUE TITLE
Discussion: Fix Pre-fetching

### ISSUE THREAD

**Issue by sinanbekar** [ericmatthys/nextjs-prefetch-with-rewrite#1]
On the website (`watch.plex.tv`), I've realized that link pre-fetching is not working so on every routing the page is fully refreshing which slows down the browse experience. I came across the Plex Engineering Medium article by chance and I found this repo also viewed the open issues on Next.js.
 
I forked the repo and implemented some demos with no pre-fetching issues.

#### GitHub forked repos:
*Rewrites with `X-Vercel-IP-Country` header*: https://github.com/sinanbekar/nextjs-prefetch-with-rewrite-country
*Rewrites with cookie*: https://github.com/sinanbekar/nextjs-prefetch-with-rewrite-cookie
*Rewrites with header (host)*: https://github.com/sinanbekar/nextjs-prefetch-with-rewrite

 
#### Vercel Deploys: 
*Rewrites with `X-Vercel-IP-Country` header*: http://nextjs-prefetch-with-rewrite-ip-country.vercel.app/
*Rewrites with cookie*: https://nextjs-prefetch-with-rewrite-cookie.vercel.app/
*Rewrites with header (host)*: https://nextjs-prefetch-with-rewrite-host.vercel.app/

### Here are my opinions:

The errors occurred in both development and production so I don't think that is related to Vercel deployments. 

Next.js rewrites with `has` worked well for me except `header` type. I tested the `cookie` type you can see in the production demo above and there was no problem so I thought that it may be the header parsing-related issue because as we all know the cookies and custom headers are available in the same HTTP Request header (but we can't access all of them by native ways in the client-side). 

Interestingly, when I specified the header key to `host` it worked well except for one thing: 

Client-side router behavior was different compared to server-side and it's possible because of the separated routers.

![Fully refresh](https://user-images.githubusercontent.com/73553699/157718258-5b755c06-022c-4b0f-8c4d-ed8ae5045a4a.png)  ![Client-side transition](https://user-images.githubusercontent.com/73553699/157718271-a7d593f7-3789-4d8c-bb6b-aa3ed69a4764.png)

**I dived a little bit deeper.**

It looks like they are passing the header only with `host` as a `req` param to `matchHas` method for the client-side router.

*--continues--*

https://github.com/vercel/next.js/blob/0355e5f63f87db489f36db8d814958cb4c2b828b/packages/next/shared/lib/router/utils/resolve-rewrites.ts#L38-L59

```js
  // packages/next/shared/lib/router/utils/resolve-rewrites.ts#L38-L59
  const handleRewrite = (rewrite: Rewrite) => {
    const matcher = customRouteMatcher(rewrite.source)
    let params = matcher(parsedAs.pathname)

    if (rewrite.has && params) {
      const hasParams = matchHas(
        {
          headers: {
            host: document.location.hostname,
          },
          cookies: document.cookie
            .split('; ')
            .reduce<Record<string, string>>((acc, item) => {
              const [key, ...value] = item.split('=')
              acc[key] = value.join('=')
              return acc
            }, {}),
        } as any,
        rewrite.has,
        parsedAs.query
      )
  .
  .  
  .

```

https://github.com/vercel/next.js/blob/0355e5f63f87db489f36db8d814958cb4c2b828b/packages/next/shared/lib/router/utils/prepare-destination.ts#L12-L48

```js
// packages/next/shared/lib/router/utils/prepare-destination.ts#L12-L48
export function matchHas(
  req: BaseNextRequest | IncomingMessage,
  has: RouteHas[],
  query: Params
): false | Params {
  const params: Params = {}

  const allMatch = has.every((hasItem) => {
    let value: undefined | string
    let key = hasItem.key

    switch (hasItem.type) {
      case 'header': {
        key = key!.toLowerCase()
        value = req.headers[key] as string
        break
      }
      case 'cookie': {
        value = (req as any).cookies[hasItem.key]
        break
      }
      case 'query': {
        value = query[key!]
        break
      }
      case 'host': {
        const { host } = req?.headers || {}
        // remove port from host if present
        const hostname = host?.split(':')[0].toLowerCase()
        value = hostname
        break
      }
      default: {
        break
      }
    }
   .
   .
   .
```

We know that there is no native way to get request headers except available in `document` (host, cookies), and **it seems that they don't want to pass the headers to the client-side**.
https://stackoverflow.com/questions/220231/accessing-the-web-pages-http-headers-in-javascript

### My Suggestions

Except for modifying core behavior, I think **cookies** can be used. On every request, Next.js middleware will get the `X-Vercel-IP-Country` header and set the cookie. Also, I use header type rewrite for fallback. But not sure if it is the best practice, currently works well even deleting the cookie manually.  It fully refreshes and sets the cookie when the cookie does not exist then continues with prefetching. But reconsideration is needed for spoofing etc.

https://github.com/sinanbekar/nextjs-prefetch-with-rewrite-country
http://nextjs-prefetch-with-rewrite-ip-country.vercel.app/

At [rewrites#header-cookie-and-query-matching](https://nextjs.org/docs/api-reference/next.config.js/rewrites#header-cookie-and-query-matching), We can see that there is an example with the HTTP GET queries (searchParams) but I think there will be no problem because it does not includes a dynamic route.

```js
      // if the header `x-authorized` is present and
      // contains a matching value, this rewrite will be applied
      {
        source: '/:path*',
        has: [
          {
            type: 'header',
            key: 'x-authorized',
            value: '(?<authorized>yes|true)',
          },
        ],
        destination: '/home?authorized=:authorized',
      },
```

I believe that there should be also a warning on the documentation.

**Comment by ericmatthys** [comment]
🕵️  I was shocked to see a GHI in this repo! haha

Your summary looks accurate and lines up with where I left this off some months ago. https://github.com/vercel/next.js/pull/24799 has some more info on not passing header values to the client.

Using middleware with cookies is a clever workaround that I hadn't considered. It definitely could work for some use cases. It's potentially too easy to manipulate as you called out. For example in https://nextjs-prefetch-with-rewrite-ip-country.vercel.app/, I can edit the cookie value in the inspector to be any country and navigating around client-side uses that updated value.

**Comment by sinanbekar** [comment]
Yes and I thought `_next/data` paths also can be handled by middleware but seems not. So I came up with a better and clean solution now and the prefetching works well I think. `req.geo.country` eq to `req.headers.get('x-vercel-ip-country')` 
see:
https://nextjs.org/docs/api-reference/next/server#nextrequest
https://nextjs.org/docs/api-reference/next/server#nextresponse

```js
import { NextResponse } from "next/server";

export function middleware(req) {
  const url = req.nextUrl.clone();
  const { pathname } = url;

  // https://nextjs.org/docs/api-reference/next/server#nextrequest
  // eq to req.headers.get('x-vercel-ip-country')
  const country = req.geo.country ?? "US"; // default

  if (pathname.startsWith("/country")) {
    return new NextResponse(null, { status: 404 });
  }

  if (pathname.startsWith("/with-rewrite")) {
    url.pathname = `/country/${country}${pathname}`;
    return NextResponse.rewrite(url);
  }
}
```
https://github.com/sinanbekar/nextjs-prefetch-with-rewrite-country
https://nextjs-prefetch-with-rewrite-ip-country.vercel.app/

Only middleware, zero `next.config.js` configuration, and for now, looks good to me. 

Official example: (https://nextjs.org/docs/api-reference/next/server#nextresponse)
```js
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export function middleware(req: NextRequest) {
  // if the request is coming from New York, redirect to the home page
  if (req.geo.city === 'New York') {
    return NextResponse.redirect('/home')
    // if the request is coming from London, rewrite to a special page
  } else if (req.geo.city === 'London') {
    return NextResponse.rewrite('/not-home')
  }

  return NextResponse.json({ message: 'Hello World!' })
}

```

**Comment by ericmatthys** [comment]
🎉 That looks promising! Do you know why the client-side router behaves differently with middleware rewrites compared to the config-based rewrites?

**Comment by sinanbekar** [comment]
I think I figured it out. Next.js handles config `has` rewrites and `middleware` rewrites completely different.

 `NextResponse.rewrite()` adds `x-middleware-rewrite` to response header while `has` rewrites does not pass any header or rewrite data from server to client (related to my first comment).


<details>
 <summary>see: packages/next/server/web/spec-extension/response.ts#L90-L96</summary>

https://github.com/vercel/next.js/blob/6611bfd31cf236342e6d31a33cf3ce50c44b2e59/packages/next/server/web/spec-extension/response.ts#L90-L96

```js
  static rewrite(destination: string | NextURL | URL) {
    return new NextResponse(null, {
      headers: {
        'x-middleware-rewrite': validateURL(destination),
      },
    })
  }
```
---
</details>

After the page loads, Next.js sends `HEAD` request (preflight) for prefetching if available and this request includes 
`x-middleware-rewrite` response header (in production Next.js caches it). 


*example `HEAD` preflight request response headers with `x-matched-path` and `x-middleware-rewrite`* :

```txt
HTTP/2 200 OK
date: xxxxx
x-matched-path: /country/[country]/with-rewrite/[slug]
x-middleware-rewrite: /country/TR/with-rewrite/faz
cache-control: public, max-age=0, must-revalidate
server: Vercel
x-vercel-id: xxxxxx
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-vercel-cache: MISS
```
---
The response headers are processed by the client-side router.

<details>
 <summary>see: packages/next/shared/lib/router/router.ts#L1986-L2032 (middleware rewrites handling)</summary>

https://github.com/vercel/next.js/blob/6611bfd31cf236342e6d31a33cf3ce50c44b2e59/packages/next/shared/lib/router/router.ts#L1986-L2032

```js
  _getPreflightData(params: {
    preflightHref: string
    shouldCache?: boolean
    isPreview: boolean
  }): Promise<PreflightData> {
    const { preflightHref, shouldCache = false, isPreview } = params
    const { href: cacheKey } = new URL(preflightHref, window.location.href)


    if (
      process.env.NODE_ENV === 'production' &&
      !isPreview &&
      shouldCache &&
      this.sde[cacheKey]
    ) {
      return Promise.resolve(this.sde[cacheKey])
    }


    return fetch(preflightHref, {
      method: 'HEAD',
      credentials: 'same-origin',
      headers: { 'x-middleware-preflight': '1' },
    })
      .then((res) => {
        if (!res.ok) {
          throw new Error(`Failed to preflight request`)
        }


        return {
          cache: res.headers.get('x-middleware-cache'),
          redirect: res.headers.get('Location'),
          refresh: res.headers.has('x-middleware-refresh'),
          rewrite: res.headers.get('x-middleware-rewrite'),
          ssr: !!res.headers.get('x-middleware-ssr'),
        }
      })
      .then((data) => {
        if (shouldCache && data.cache !== 'no-cache') {
          this.sde[cacheKey] = data
        }


        return data
      })
      .catch((err) => {
        delete this.sde[cacheKey]
        throw err
      })
  }
```
---
</details>

<details>

<summary>see: packages/next/shared/lib/router/router.ts#L1172-L1197 (middleware rewrites handling)</summary>

https://github.com/vercel/next.js/blob/6611bfd31cf236342e6d31a33cf3ce50c44b2e59/packages/next/shared/lib/router/router.ts#L1172-L1197

```js
      const effect = await this._preflightRequest({
        as,
        cache: process.env.NODE_ENV === 'production',
        pages,
        pathname,
        query,
        locale: nextState.locale,
        isPreview: nextState.isPreview,
      })


      if (effect.type === 'rewrite') {
        query = { ...query, ...effect.parsedAs.query }
        resolvedAs = effect.asPath
        pathname = effect.resolvedHref
        parsed.pathname = effect.resolvedHref
        url = formatWithValidation(parsed)
      } else if (effect.type === 'redirect' && effect.newAs) {
        return this.change(method, effect.newUrl, effect.newAs, options)
      } else if (effect.type === 'redirect' && effect.destination) {
        window.location.href = effect.destination
        return new Promise(() => {})
      } else if (effect.type === 'refresh' && as !== window.location.pathname) {
        window.location.href = as
        return new Promise(() => {})
      }
    }
.
.
.
```
It handles router events after these lines.
---
</details>

Not related to response headers:

<details>

<summary>see: packages/next/shared/lib/router/router.ts#L1114-L1146 (has rewrites handling)</summary>


`resolveRewrites()` method code block available in my first comment.

https://github.com/vercel/next.js/blob/6611bfd31cf236342e6d31a33cf3ce50c44b2e59/packages/next/shared/lib/router/router.ts#L1114-L1146

```js
      if (process.env.__NEXT_HAS_REWRITES && as.startsWith('/')) {
        const rewritesResult = resolveRewrites(
          addBasePath(addLocale(cleanedAs, nextState.locale)),
          pages,
          rewrites,
          query,
          (p: string) => resolveDynamicRoute(p, pages),
          this.locales
        )


        if (rewritesResult.externalDest) {
          location.href = as
          return true
        }
        resolvedAs = rewritesResult.asPath


        if (rewritesResult.matchedPage && rewritesResult.resolvedHref) {
          // if this directly matches a page we need to update the href to
          // allow the correct page chunk to be loaded
          pathname = rewritesResult.resolvedHref
          parsed.pathname = addBasePath(pathname)
          url = formatWithValidation(parsed)
        }
      } else {
        parsed.pathname = resolveDynamicRoute(pathname, pages)


        if (parsed.pathname !== pathname) {
          pathname = parsed.pathname
          parsed.pathname = addBasePath(pathname)
          url = formatWithValidation(parsed)
        }
      }
    }
```

---
</details>

The client-side router decides between server-side transition (hard navigation) and client-side transition (prefetching). If the preflight error occurs or somehow the rewrite fails it fallbacks to the server-side transition and we can see this when has rewrite config available (with header value included in destination).

<details>

<summary>see: packages/next/shared/lib/router/router.ts#L1074-L1089</summary>

https://github.com/vercel/next.js/blob/6611bfd31cf236342e6d31a33cf3ce50c44b2e59/packages/next/shared/lib/router/router.ts#L1074-L1089

```js
    // The build manifest needs to be loaded before auto-static dynamic pages
    // get their query parameters to allow ensuring they can be parsed properly
    // when rewritten to
    let pages: any, rewrites: any
    try {
      ;[pages, { __rewrites: rewrites }] = await Promise.all([
        this.pageLoader.getPageList(),
        getClientBuildManifest(),
        this.pageLoader.getMiddlewareList(),
      ])
    } catch (err) {
      // If we fail to resolve the page list or client-build manifest, we must
      // do a server-side transition:
      window.location.href = as
      return false
    }
```
</details>
